"""add members table

Revision ID: 7a4de08201a1
Revises: 5afd5c7538ca
Create Date: 2026-09-21 19:23:46.935564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4de08201a1'
down_revision = '5afd5c7538ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('gps_address', sa.String(length=50), nullable=True),
    sa.Column('hometown', sa.String(length=80), nullable=True),
    sa.Column('street_name', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('parent_name', sa.String(length=120), nullable=True),
    sa.Column('parent_relationship', sa.String(length=40), nullable=True),
    sa.Column('member_type', sa.String(length=80), nullable=True),
    sa.Column('holyghost_baptism', sa.Boolean(), nullable=True),
    sa.Column('date_of_holy_spirit_baptism', sa.Date(), nullable=True),
    sa.Column('water_baptism', sa.Boolean(), nullable=True),
    sa.Column('date_of_baptism', sa.Date(), nullable=True),
    sa.Column('date_of_conversion', sa.Date(), nullable=True),
    sa.Column('date_of_joining_us', sa.Date(), nullable=True),
    sa.Column('place_of_baptism', sa.String(length=120), nullable=True),
    sa.Column('officiating_minister_baptism', sa.String(length=120), nullable=True),
    sa.Column('officiating_ministers_district', sa.String(length=120), nullable=True),
    sa.Column('communicant', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('level_of_education', sa.String(length=120), nullable=True),
    sa.Column('dedicated', sa.Boolean(), nullable=True),
    sa.Column('dedication_date', sa.Date(), nullable=True),
    sa.Column('officiating_minister_dedication', sa.String(length=120), nullable=True),
    sa.Column('church_where_dedication_was_done', sa.String(length=120), nullable=True),
    sa.Column('membership_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_membership_status'), ['membership_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_membership_status'))

    op.drop_table('members')
    # ### end Alembic commands ###
